# Generated by Django 6.1 on 2026-08-11 21:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('cluster_id', models.IntegerField(primary_key=True, serialize=False)),
                ('centroid_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('centroid_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('silhouette_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('location_lat', models.DecimalField(decimal_places=6, default=6.6885, max_digits=9)),
                ('location_lng', models.DecimalField(decimal_places=6, default=-1.6244, max_digits=9)),
                ('preferred_causes', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('cause_description', models.TextField()),
                ('district', models.CharField(default='Kumasi Metropolitan', max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('gps_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('gps_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('children_count', models.PositiveIntegerField(default=0)),
                ('funding_gap', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('cluster_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='institution_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterestStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_statements', to='api.donor')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('similarity_score', models.FloatField()),
                ('priority_score', models.FloatField()),
                ('final_rank', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.donor')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='api.institution')),
                ('statement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.intereststatement')),
            ],
            options={
                'ordering': ['final_rank'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=255)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='api.donor')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('donor', 'Donor'), ('institution_admin', 'Institution Administrator'), ('system_admin', 'System Administrator')], default='donor', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
