# Generated by Django 6.1 on 2026-08-12 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='last_donation_date',
            new_name='funding_last_updated',
        ),
    ]
