# Generated by Django 6.1 on 2026-08-18 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_last_donation_date_to_funding_last_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='most_lacking_need',
            field=models.CharField(blank=True, default='Food & Groceries', max_length=100),
        ),
    ]
